# Generated by Django 6.0.4 on 2026-04-09 00:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parentplayerrelation',
            name='can_limit_player_access',
        ),
        migrations.RemoveField(
            model_name='parentplayerrelation',
            name='can_manage_payments',
        ),
        migrations.RemoveField(
            model_name='parentplayerrelation',
            name='can_view_progress',
        ),
        migrations.RemoveField(
            model_name='parentplayerrelation',
            name='can_view_schedule',
        ),
        migrations.RemoveField(
            model_name='parentplayerrelation',
            name='parent_email',
        ),
        migrations.CreateModel(
            name='PlayerAccessPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_parent_managed', models.BooleanField(default=False)),
                ('can_self_confirm_attendance', models.BooleanField(default=True)),
                ('can_self_make_payments', models.BooleanField(default=True)),
                ('can_self_submit_absence_reasons', models.BooleanField(default=True)),
                ('can_self_approve_schedule_confirmations', models.BooleanField(default=True)),
                ('can_self_update_emergency_contact', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='access_policy', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
