# Generated by Django 6.0.4 on 2026-04-11 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_notification"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="PasswordResetOTP",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("otp_hash", models.CharField(max_length=128)),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("expires_at", models.DateTimeField()),
                        (
                            "user",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="password_reset_otps",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                    ],
                    options={
                        "indexes": [
                            models.Index(
                                fields=["user", "expires_at"],
                                name="core_passwo_user_id_7b76f5_idx",
                            )
                        ],
                    },
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    CREATE TABLE IF NOT EXISTS `core_passwordresetotp` (
                        `id` bigint NOT NULL AUTO_INCREMENT,
                        `otp_hash` varchar(128) NOT NULL,
                        `created_at` datetime(6) NOT NULL,
                        `expires_at` datetime(6) NOT NULL,
                        `user_id` bigint NOT NULL,
                        PRIMARY KEY (`id`),
                        KEY `core_passwo_user_id_7b76f5_idx` (`user_id`, `expires_at`),
                        CONSTRAINT `core_passwordresetotp_user_id_fk`
                            FOREIGN KEY (`user_id`) REFERENCES `core_user` (`id`)
                            ON DELETE CASCADE
                    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
                    """,
                    reverse_sql="DROP TABLE IF EXISTS `core_passwordresetotp`;",
                ),
            ],
        ),
    ]
