# Generated by Django 6.0.4 on 2026-04-12 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_password_reset_otp"),
        ("core", "0008_password_reset_verification_and_assigned_role"),
    ]

    operations = []
