# Generated by Django 6.0.4 on 2026-04-12 15:58

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_merge_password_reset_heads"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="default_monthly_player_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("75.00"),
                help_text="Default amount for automatic monthly player dues (per team roster line).",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="parentplayerrelation",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending director approval"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="approved",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="assigned_account_role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("player", "Player"),
                    ("parent", "Parent"),
                    ("coach", "Coach"),
                    ("director", "Director"),
                ],
                default="",
                help_text="Primary app role set and maintained by club directors.",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="PaymentSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("club", "Entire club"),
                            ("team", "Specific team"),
                            ("player", "Specific player"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("once", "Once"),
                            ("hourly", "Hourly"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        max_length=10,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("description", models.CharField(max_length=255)),
                ("start_date", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_schedules",
                        to="core.club",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_payment_schedules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="targeted_payment_schedules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_schedules",
                        to="core.team",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PlayerFeeRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(default="Club fee", max_length=255)),
                ("amount_due", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("due_date", models.DateField()),
                (
                    "billing_period_start",
                    models.DateField(
                        blank=True,
                        db_index=True,
                        help_text="First day of the calendar month this recurring fee belongs to (if set).",
                        null=True,
                    ),
                ),
                (
                    "schedule_occurrence_key",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Stable id for one row materialized from a payment schedule (due date + player + schedule).",
                        max_length=128,
                    ),
                ),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_fee_records",
                        to="core.club",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_fee_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fee_records",
                        to="core.paymentschedule",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="player_fee_records",
                        to="core.team",
                    ),
                ),
            ],
            options={
                "ordering": ["-due_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="FeePaymentLedgerEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                ("note", models.CharField(blank=True, max_length=255)),
                (
                    "fee_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ledger_entries",
                        to="core.playerfeerecord",
                    ),
                ),
            ],
            options={
                "ordering": ["-recorded_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="DirectorPaymentAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("fee_created", "Fee created"),
                            ("payment_recorded", "Payment recorded"),
                            ("reminder_sent", "Payment reminder sent"),
                            ("receipt_sent", "Receipt emailed"),
                            ("bulk_statements_sent", "Bulk statements emailed"),
                            ("monthly_fees_materialized", "Monthly fees materialized"),
                        ],
                        max_length=32,
                    ),
                ),
                ("detail", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_audit_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_audit_logs",
                        to="core.club",
                    ),
                ),
                (
                    "fee_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="core.playerfeerecord",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="playerfeerecord",
            constraint=models.UniqueConstraint(
                fields=("club", "player", "team", "billing_period_start"),
                name="unique_player_team_billing_period_fee",
            ),
        ),
    ]
