# Generated by Django 6.0.4 on 2026-04-12 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_consolidated_unpublished_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='training_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incomplete_attendance_notifications', to='core.trainingsession'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('session', 'Session'), ('schedule', 'Schedule'), ('manual', 'Manual'), ('attendance_incomplete', 'Attendance incomplete')], default='manual', max_length=32),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(condition=models.Q(('category', 'attendance_incomplete'), ('training_session__isnull', False)), fields=('recipient', 'training_session', 'category'), name='core_notification_unique_attendance_incomplete'),
        ),
    ]
