# Generated by Django 6.0.4 on 2026-04-13 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_remove_useraccountrole"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamSkillDashboardMetric",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "skill_category",
                    models.CharField(
                        choices=[
                            ("attack", "Attack"),
                            ("defense", "Defense"),
                            ("serve", "Serve"),
                            ("block", "Block"),
                        ],
                        max_length=20,
                    ),
                ),
                ("attendance_rate", models.DecimalField(decimal_places=2, max_digits=5)),
                ("average_performance", models.DecimalField(decimal_places=2, max_digits=5)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_dashboard_metrics",
                        to="core.team",
                    ),
                ),
            ],
            options={
                "ordering": ["team_id", "skill_category"],
            },
        ),
        migrations.CreateModel(
            name="TeamRosterPlayerStat",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("spikes", models.PositiveIntegerField(default=0)),
                ("blocks", models.PositiveIntegerField(default=0)),
                ("serve_percentage", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "prior_serve_percentage",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roster_player_stats",
                        to="core.team",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_roster_stats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["team_id", "player__first_name", "player__last_name"],
            },
        ),
        migrations.CreateModel(
            name="TeamCoachFeedback",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("body", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("addressed", "Addressed")],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "coach",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coach_feedback_authored",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coach_feedback_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coach_feedback_entries",
                        to="core.team",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="teamrosterplayerstat",
            constraint=models.UniqueConstraint(fields=("team", "player"), name="unique_team_roster_player_stat"),
        ),
        migrations.AddConstraint(
            model_name="teamskilldashboardmetric",
            constraint=models.UniqueConstraint(
                fields=("team", "skill_category"),
                name="unique_team_skill_dashboard_metric",
            ),
        ),
    ]
