# Generated by Django 6.0.4 on 2026-04-14 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_contact_submission'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='registrationotp',
            new_name='core_regist_email_07ff9f_idx',
            old_name='core_regist_email_9f6506_idx',
        ),
    ]
