# Generated by Django 6.0.4 on 2026-04-23 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_trainingsession_match_completion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('session', 'Session'), ('schedule', 'Schedule'), ('manual', 'Manual'), ('match_request', 'Match request'), ('attendance_incomplete', 'Attendance incomplete')], default='manual', max_length=32),
        ),
    ]
