# Generated by Django 6.0.4 on 2026-04-24 06:41

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_notification_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tournament_type', models.CharField(choices=[('pools', 'Round-robin pools'), ('bracket', 'Elimination bracket'), ('hybrid', 'Pools + bracket')], max_length=16)),
                ('number_of_teams', models.PositiveIntegerField()),
                ('pool_count', models.PositiveIntegerField(default=0)),
                ('teams_per_pool', models.PositiveIntegerField(default=0)),
                ('match_duration_minutes', models.PositiveIntegerField(default=90)),
                ('scoring_format', models.CharField(default='Best of 3 to 25', max_length=120)),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField(default=datetime.time(18, 0))),
                ('venue', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('generated', 'Generated')], default='generated', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournaments', to='core.club')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tournaments', to=settings.AUTH_USER_MODEL)),
                ('teams', models.ManyToManyField(blank=True, related_name='tournaments', to='core.team')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TournamentPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('pool_order', models.PositiveIntegerField(default=1)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pools', to='core.tournament')),
            ],
            options={
                'ordering': ['pool_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TournamentFixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_type', models.CharField(choices=[('pool', 'Pool'), ('bracket', 'Bracket')], max_length=16)),
                ('round_number', models.PositiveIntegerField(default=1)),
                ('round_label', models.CharField(max_length=120)),
                ('fixture_order', models.PositiveIntegerField(default=1)),
                ('placeholder_home_label', models.CharField(blank=True, max_length=120)),
                ('placeholder_away_label', models.CharField(blank=True, max_length=120)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('away_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='away_tournament_fixtures', to='core.team')),
                ('home_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_tournament_fixtures', to='core.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixtures', to='core.tournament')),
                ('training_session', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_fixture', to='core.trainingsession')),
                ('pool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fixtures', to='core.tournamentpool')),
            ],
            options={
                'ordering': ['stage_type', 'round_number', 'fixture_order', 'id'],
            },
        ),
    ]
