# Generated by Django 6.0.4 on 2026-04-24 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_tournament_tournamentpool_tournamentfixture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournament",
            name="status",
            field=models.CharField(
                choices=[("generated", "Generated"), ("cancelled", "Cancelled")],
                default="generated",
                max_length=16,
            ),
        ),
    ]
