# Generated by Django 6.0.4 on 2026-04-25 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pool_stage', 'Pool Stage'), ('bracket_stage', 'Bracket Stage'), ('completed', 'Completed'), ('generated', 'Generated'), ('cancelled', 'Cancelled')], default='generated', max_length=16),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournament_type',
            field=models.CharField(choices=[('pools', 'Round-robin pools'), ('bracket', 'Elimination bracket'), ('hybrid', 'Pools + bracket'), ('pool_only', 'Pool Play'), ('bracket_only', 'Bracket'), ('pool_and_bracket', 'Pool + Bracket')], max_length=16),
        ),
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_groups', to='core.tournament')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Standing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wins', models.PositiveIntegerField(default=0)),
                ('losses', models.PositiveIntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('points_for', models.IntegerField(default=0)),
                ('points_against', models.IntegerField(default=0)),
                ('point_difference', models.IntegerField(default=0)),
                ('set_ratio', models.FloatField(default=0.0)),
                ('rank', models.PositiveIntegerField(default=1)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='core.pool')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_standings', to='core.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='core.tournament')),
            ],
            options={
                'ordering': ['pool_id', 'rank', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TournamentMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bracket_round', models.CharField(blank=True, max_length=64)),
                ('match_number', models.PositiveIntegerField(default=1)),
                ('team_a_score', models.PositiveIntegerField(blank=True, null=True)),
                ('team_b_score', models.PositiveIntegerField(blank=True, null=True)),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=16)),
                ('next_match_slot', models.CharField(blank=True, max_length=8)),
                ('can_edit_result', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loser_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_matches_lost', to='core.team')),
                ('next_match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feeders', to='core.tournamentmatch')),
                ('pool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='core.pool')),
                ('team_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_matches_as_team_a', to='core.team')),
                ('team_b', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_matches_as_team_b', to='core.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_matches', to='core.tournament')),
                ('winner_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_matches_won', to='core.team')),
            ],
            options={
                'ordering': ['match_number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TournamentTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed', models.PositiveIntegerField(default=1)),
                ('pool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_teams', to='core.pool')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_tournaments', to='core.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_teams', to='core.tournament')),
            ],
            options={
                'ordering': ['seed', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='pool',
            constraint=models.UniqueConstraint(fields=('tournament', 'name'), name='uniq_tournament_pool_name'),
        ),
        migrations.AddConstraint(
            model_name='standing',
            constraint=models.UniqueConstraint(fields=('tournament', 'pool', 'team'), name='uniq_standing_team_per_pool'),
        ),
        migrations.AddConstraint(
            model_name='tournamentteam',
            constraint=models.UniqueConstraint(fields=('tournament', 'team'), name='uniq_tournament_team'),
        ),
        migrations.AddConstraint(
            model_name='tournamentteam',
            constraint=models.UniqueConstraint(fields=('tournament', 'seed'), name='uniq_tournament_seed'),
        ),
    ]
