# Generated by Django 6.0.4 on 2026-04-26 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_tournament_status_default_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='tournament_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_training_sessions', to='core.tournamentmatch'),
        ),
        migrations.AddConstraint(
            model_name='trainingsession',
            constraint=models.UniqueConstraint(condition=models.Q(('tournament_match__isnull', False)), fields=('tournament_match', 'team'), name='uniq_trainingsession_tournament_match_team'),
        ),
    ]
