# Generated by Django 6.0.4 on 2026-04-26 08:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_training_session_tournament_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='court_count',
            field=models.PositiveIntegerField(default=1, help_text='Parallel courts for scheduling (not the same as pool count).'),
        ),
        migrations.AddField(
            model_name='tournamentmatch',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Override tournament match length for this game (start + duration = end).', null=True),
        ),
        migrations.AddField(
            model_name='tournamentmatch',
            name='pool_round_number',
            field=models.PositiveIntegerField(blank=True, help_text='Round index within pool play (1-based), for display only.', null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='start_time',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
    ]
