from django.urls import path

from . import payment_views
from .views import (
    add_parent_association,
    add_team_member,
    directors_pending_parent_links,
    directors_resolve_parent_link,
    clear_training_session,
    coach_team_dashboard,
    coach_training_session_attendance,
    create_club,
    create_team,
    confirm_training_session,
    directors_pending_users,
    directors_reject_user,
    directors_set_user_account_role,
    directors_user_directory,
    directors_verify_user,
    login,
    password_reset_confirm,
    password_reset_request,
    mark_notifications_read,
    manage_player_parent_access,
    manage_training_session,
    me,
    parent_child_attendance_history,
    player_team_attendance_summary,
    request_parent_link_to_player,
    notifications,
    remove_parent_association,
    remove_team_captain,
    remove_team_member,
    register,
    register_verify,
    remind_unconfirmed_training_session,
    send_team_notification,
    set_team_captain,
    team_attendance_analytics,
    team_attendance_summary,
    team_schedule,
    team_training_sessions,
    update_team_details,
    update_team_member_data,
    view_team_members,
)

app_name = "core"

urlpatterns = [
    path("auth/login/", login, name="login"),
    path("auth/password-reset/request/", password_reset_request, name="password-reset-request"),
    path("auth/password-reset/confirm/", password_reset_confirm, name="password-reset-confirm"),
    path("directors/pending-users/", directors_pending_users, name="directors-pending-users"),
    path("directors/users/directory/", directors_user_directory, name="directors-user-directory"),
    path(
        "directors/users/<int:user_id>/account-role/",
        directors_set_user_account_role,
        name="directors-set-account-role",
    ),
    path("directors/users/<int:user_id>/verify/", directors_verify_user, name="directors-verify-user"),
    path("directors/users/<int:user_id>/reject/", directors_reject_user, name="directors-reject-user"),
    path("auth/me/", me, name="me"),
    path("me/parent/child-attendance/", parent_child_attendance_history, name="parent-child-attendance"),
    path("me/parent-link-request/", request_parent_link_to_player, name="request-parent-link"),
    path(
        "directors/parent-link-requests/",
        directors_pending_parent_links,
        name="directors-pending-parent-links",
    ),
    path(
        "directors/parent-link-requests/<int:relation_id>/",
        directors_resolve_parent_link,
        name="directors-resolve-parent-link",
    ),
    path("notifications/", notifications, name="notifications"),
    path("notifications/read/", mark_notifications_read, name="mark-notifications-read"),
    path("notifications/send/", send_team_notification, name="send-team-notification"),
    path("clubs/create/", create_club, name="create-club"),
    path(
        "clubs/<int:club_id>/director/payments/overview/",
        payment_views.director_payment_overview,
        name="director-payment-overview",
    ),
    path(
        "clubs/<int:club_id>/director/payments/rows/",
        payment_views.director_payment_rows,
        name="director-payment-rows",
    ),
    path(
        "clubs/<int:club_id>/director/payments/logs/",
        payment_views.director_payment_logs,
        name="director-payment-logs",
    ),
    path(
        "clubs/<int:club_id>/director/payments/lookup-player/",
        payment_views.director_payment_lookup_player,
        name="director-payment-lookup-player",
    ),
    path(
        "clubs/<int:club_id>/director/payments/records/",
        payment_views.director_create_fee_record,
        name="director-create-fee-record",
    ),
    path(
        "clubs/<int:club_id>/director/payments/records/<int:record_id>/payment/",
        payment_views.director_record_fee_payment,
        name="director-record-fee-payment",
    ),
    path(
        "clubs/<int:club_id>/director/payments/records/<int:record_id>/receipt.pdf/",
        payment_views.director_download_receipt_pdf,
        name="director-download-receipt-pdf",
    ),
    path(
        "clubs/<int:club_id>/director/payments/records/<int:record_id>/reminder/",
        payment_views.director_send_payment_reminder,
        name="director-send-payment-reminder",
    ),
    path(
        "clubs/<int:club_id>/director/payments/records/<int:record_id>/receipt/",
        payment_views.director_send_receipt,
        name="director-send-receipt",
    ),
    path(
        "clubs/<int:club_id>/director/payments/renewals-today/email-player/",
        payment_views.director_email_renewals_due_today_for_player,
        name="director-email-renewals-today-player",
    ),
    path(
        "clubs/<int:club_id>/director/payments/renewals-today/",
        payment_views.director_renewals_due_today,
        name="director-renewals-due-today",
    ),
    path(
        "clubs/<int:club_id>/director/payments/materialize-month/",
        payment_views.director_materialize_monthly_fees,
        name="director-materialize-monthly-fees",
    ),
    path(
        "clubs/<int:club_id>/director/payments/bulk-email-renewals-today/",
        payment_views.director_bulk_email_renewals_due_today,
        name="director-bulk-email-renewals-today",
    ),
    path(
        "clubs/<int:club_id>/director/payments/outstanding-notice/",
        payment_views.director_email_outstanding_notice_for_player,
        name="director-email-outstanding-notice",
    ),
    path(
        "teams/<int:team_id>/payments/",
        payment_views.team_player_payments,
        name="team-player-payments",
    ),
    path(
        "teams/<int:team_id>/player-payments/",
        payment_views.player_team_payments,
        name="player-team-payments",
    ),
    path("my-fees/", payment_views.my_fees, name="my-fees"),
    path(
        "my-fees/<int:record_id>/pay/",
        payment_views.record_self_payment,
        name="record-self-payment",
    ),
    path(
        "clubs/<int:club_id>/payment-schedules/",
        payment_views.list_payment_schedules,
        name="list-payment-schedules",
    ),
    path(
        "clubs/<int:club_id>/payment-schedules/create/",
        payment_views.create_payment_schedule,
        name="create-payment-schedule",
    ),
    path(
        "clubs/<int:club_id>/payment-schedules/<int:schedule_id>/deactivate/",
        payment_views.deactivate_payment_schedule,
        name="deactivate-payment-schedule",
    ),
    path(
        "clubs/<int:club_id>/payment-schedules/<int:schedule_id>/delete/",
        payment_views.delete_payment_schedule,
        name="delete-payment-schedule",
    ),
    path("clubs/<int:club_id>/teams/create/", create_team, name="create-team"),
    path("players/<int:player_id>/parents/", add_parent_association, name="add-parent-association"),
    path(
        "players/<int:player_id>/parents/<int:parent_id>/",
        remove_parent_association,
        name="remove-parent-association",
    ),
    path(
        "players/<int:player_id>/parent-management/",
        manage_player_parent_access,
        name="manage-player-parent-access",
    ),
    path("register/", register, name="register"),
    path("register/verify/", register_verify, name="register-verify"),
    path("teams/<int:team_id>/members/", view_team_members, name="view-team-members"),
    path("teams/<int:team_id>/schedule/", team_schedule, name="team-schedule"),
    path(
        "teams/<int:team_id>/training-sessions/",
        team_training_sessions,
        name="team-training-sessions",
    ),
    path(
        "teams/<int:team_id>/attendance/trends/",
        team_attendance_analytics,
        name="team-attendance-trends",
    ),
    path(
        "teams/<int:team_id>/attendance/summary/",
        team_attendance_summary,
        name="team-attendance-summary",
    ),
    path(
        "teams/<int:team_id>/players/<int:player_id>/attendance/summary/",
        player_team_attendance_summary,
        name="player-team-attendance-summary",
    ),
    path(
        "teams/<int:team_id>/coach-dashboard/",
        coach_team_dashboard,
        name="coach-team-dashboard",
    ),
    path(
        "training-sessions/<int:session_id>/",
        manage_training_session,
        name="manage-training-session",
    ),
    path(
        "training-sessions/<int:session_id>/confirm/",
        confirm_training_session,
        name="confirm-training-session",
    ),
    path(
        "training-sessions/<int:session_id>/remind-unconfirmed/",
        remind_unconfirmed_training_session,
        name="remind-unconfirmed-training-session",
    ),
    path(
        "training-sessions/<int:session_id>/attendance/",
        coach_training_session_attendance,
        name="coach-training-session-attendance",
    ),
    path(
        "training-sessions/<int:session_id>/clear/",
        clear_training_session,
        name="clear-training-session",
    ),
    path("teams/<int:team_id>/members/add/", add_team_member, name="add-team-member"),
    path(
        "teams/<int:team_id>/captains/<int:player_id>/",
        set_team_captain,
        name="set-team-captain",
    ),
    path(
        "teams/<int:team_id>/captains/<int:player_id>/remove/",
        remove_team_captain,
        name="remove-team-captain",
    ),
    path(
        "teams/<int:team_id>/members/<int:target_user_id>/remove/",
        remove_team_member,
        name="remove-team-member",
    ),
    path("teams/<int:team_id>/update/", update_team_details, name="update-team-details"),
    path(
        "teams/<int:team_id>/members/<int:target_user_id>/team-data/",
        update_team_member_data,
        name="update-team-member-data",
    ),
]
